<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dfg" nsURI="http://it/diee/unica/mdc/model" nsPrefix="it.diee.unica.mdc.model">
  <eClassifiers xsi:type="ecore:EClass" name="DfgGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" upperBound="-1"
        eType="#//DfgVertex" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//DfgEdge" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DfgVertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappings" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbors" upperBound="-1"
        eType="#//DfgVertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connecting" upperBound="-1"
        eType="#//DfgEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DfgEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertex1" eType="#//DfgVertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertex2" eType="#//DfgVertex"/>
  </eClassifiers>
</ecore:EPackage>
